export const M={
members:{i:'👥',t:'Members',d:'Members, families & volunteers in one secure database',
stats:[['Total Members','1,248'],['Families','342'],['Volunteers','86'],['New This Month','37']],
cols:['Name','Phone','Family','Group','Status'],
rows:[['Abdullahi Musa','0803 123 4567','Musa Family','Adult','Active'],['Fatima Bello','0805 234 5678','Bello Family','Women','Active'],['Ibrahim Sani','0806 345 6789','Sani Family','Youth','Active'],['Aisha Lawal','0812 456 7890','Lawal Family','Women','Active'],['Usman Haruna','0813 567 8901','Haruna Family','Adult','Pending']]},
donations:{i:'💰',t:'Donations & Funds',d:'Zakat, Sadaqah, Waqf, development and community funds',
stats:[['Zakat Fund','₦2,340,000'],['Sadaqah Fund','₦1,875,000'],['Mosque Development','₦4,200,000'],['Waqf','₦980,000']],
cols:['Donor','Fund','Amount','Date','Status'],
rows:[['Abdul Kareem','Zakat','₦500,000','Oct 24, 2025','Paid'],['Fatima Yusuf','Sadaqah','₦300,000','Oct 23, 2025','Paid'],['Ibrahim Sani','Development','₦200,000','Oct 22, 2025','Paid'],['Aisha Ali','Waqf','₦150,000','Oct 21, 2025','Pending'],['Mustapha Bello','Education','₦120,000','Oct 20, 2025','Paid']]},
finance:{i:'📊',t:'Finance',d:'Income, expenses, budgets and transparent reports',
stats:[['Total Income','₦12,480,000'],['Total Expenses','₦4,320,000'],['Net Balance','₦8,160,000'],['Budget Used','35%']],
cols:['Description','Category','Amount','Date','Type'],
rows:[['Zakat Donation','Zakat','₦500,000','Oct 24, 2025','Income'],['Mosque Utilities','Utilities','₦150,000','Oct 23, 2025','Expense'],['Education Fund','Education','₦200,000','Oct 22, 2025','Income'],['Staff Salary','Payroll','₦250,000','Oct 18, 2025','Expense']]},
events:{i:'📅',t:'Events & Programs',d:'Jumu\'ah, lectures, Ramadan activities and community events',
stats:[['Total Events','12'],['Jumu\'ah Programs','4'],['This Week','3'],['RSVPs','412']],
cols:['Event','Date','Time','Venue','Status'],
rows:[['Jumu\'ah Khutbah','Oct 25','1:00 PM','Main Masjid','Confirmed'],['Qur\'an Tafsir Class','Oct 28','6:30 PM','Education Hall','Confirmed'],['Ramadan Preparation Talk','Nov 02','5:00 PM','Conference Room','Scheduled'],['Charity Drive','Nov 08','9:00 AM','Masjid Compound','Scheduled']]},
school:{i:'📚',t:'Islamiyyah & Qur\'an School',d:'Students, parents, teachers, attendance and fees',
stats:[['Students','248'],['Classes','8'],['Teachers','14'],['Fees Collected','₦1,420,000']],
cols:['Class','Level','Teacher','Students','Status'],
rows:[['Qur\'an Recitation','Beginner','Ust. Ibrahim Musa','32','Active'],['Tafsir Class','Intermediate','Ust. Ahmad Bello','28','Active'],['Islamic Jurisprudence','Advanced','Dr. Fatima Sani','18','Active'],['Arabic Language','Beginner','Ust. Yusuf Ibrahim','24','Active'],['Hifz Program','All Levels','Ust. Musa Abdullahi','12','Active']]},
announce:{i:'📢',t:'Announcements',d:'Reach everyone by app, WhatsApp, SMS and the mosque display',
stats:[['Sent This Month','18'],['Reach','1,106'],['Open Rate','87%'],['Scheduled','3']],
cols:['Title','Audience','Channel','Date','Status'],
rows:[['Jumu\'ah time change','All Members','WhatsApp + SMS','Oct 22','Sent'],['Ramadan Timetable','All Members','App + Display','Oct 20','Sent'],['Youth Circle Reminder','Youth','WhatsApp','Oct 26','Scheduled'],['Fundraising Update','Donors','SMS','Oct 27','Draft']]},
volunteers:{i:'🤝',t:'Volunteers & Committees',d:'Departments, committees and mosque responsibilities',
stats:[['Volunteers','86'],['Committees','7'],['Open Tasks','12'],['Hours This Month','340']],
cols:['Name','Committee','Role','Phone','Status'],
rows:[['Yusuf Garba','Welfare','Chairman','0807 111 2233','Active'],['Zainab Kabir','Education','Coordinator','0809 222 3344','Active'],['Hassan Aliyu','Security','Lead','0802 333 4455','Active'],['Maryam Idris','Ramadan','Secretary','0810 444 5566','Pending']]},
welfare:{i:'❤️',t:'Welfare',d:'Confidential case management with restricted access',
stats:[['Open Cases','23'],['Assisted This Year','141'],['Disbursed','₦2,150,000'],['Pending Review','6']],
cols:['Case ID','Type','Amount','Officer','Status'],
rows:[['WF-0142','Medical Support','₦80,000','Welfare Officer','Approved'],['WF-0143','School Fees','₦45,000','Welfare Officer','Pending'],['WF-0144','Food Package','₦25,000','Welfare Officer','Approved'],['WF-0145','Rent Assistance','₦120,000','Welfare Officer','Review']]},
facilities:{i:'🏛️',t:'Facilities & Halls',d:'Halls, classrooms and booking requests',
stats:[['Facilities','9'],['Bookings This Month','27'],['Pending Requests','4'],['Income','₦340,000']],
cols:['Facility','Requested By','Date','Purpose','Status'],
rows:[['Conference Hall','Sani Family','Nov 03','Naming Ceremony','Approved'],['Education Hall','Youth Circle','Nov 05','Seminar','Approved'],['Main Hall','Bello Family','Nov 12','Wedding Reception','Pending'],['Classroom 1','Qur\'an School','Nov 14','Exam','Approved']]},
nikah:{i:'💍',t:'Nikah Management',d:'Requests, schedules, documentation and certificates',
stats:[['Requests','31'],['Scheduled','8'],['Completed','19'],['Docs Pending','4']],
cols:['Couple','Date','Imam','Documents','Status'],
rows:[['Ahmad & Khadija','Nov 09','Imam Abubakar','Complete','Scheduled'],['Sulaiman & Hauwa','Nov 16','Imam Abubakar','Incomplete','Pending'],['Bashir & Rakiya','Oct 18','Imam Abubakar','Complete','Completed']]},
comms:{i:'📲',t:'WhatsApp & SMS',d:'Bulk messaging, templates and delivery tracking',
stats:[['Messages Sent','4,820'],['WhatsApp','3,100'],['SMS','1,720'],['Delivered','98%']],
cols:['Campaign','Channel','Recipients','Date','Status'],
rows:[['Jumu\'ah Reminder','WhatsApp','1,106','Oct 24','Sent'],['Zakat Appeal','SMS','820','Oct 21','Sent'],['Ramadan Timetable','WhatsApp','1,106','Oct 19','Sent'],['Charity Drive','SMS','900','Oct 30','Scheduled']]},
roles:{i:'🔐',t:'Roles & Access',d:'Each officer sees only what they need',
stats:[['Administrators','9'],['Roles','7'],['Audit Events Today','64'],['2FA Enabled','100%']],
cols:['Name','Role','Access','Last Login','Status'],
rows:[['Imam Abubakar','Imam','Nikah, Events, Announcements','Today','Active'],['Alh. Sani Musa','Treasurer','Donations, Finance','Today','Active'],['Hajiya Aisha','Secretary','Members, Communication','Yesterday','Active'],['Ust. Yusuf','Education Officer','School','Today','Active'],['Mal. Idris','Welfare Officer','Welfare','2 days ago','Active']]}
}
